env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - standard-with-typescript
  - plugin:vue/vue3-essential
  - @vue/prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
