AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Query directSessionAccess

Parameters:
  ApiId:
    Type: String
  SessionTableDataSourceName:
    Type: String

Resources:
  DirectSessionAccessQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: directSessionAccess
      DataSourceName: !Ref SessionTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/get-item-where-id-args-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
