version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "dependabot/github-actions/main"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: ./sam/lambda/nodejs
    schedule:
      interval: daily
    target-branch: "dependabot/npm/sam/main"
  - package-ecosystem: npm
    directory: ./client
    schedule:
      interval: daily
    target-branch: "dependabot/npm/client/main"
    groups:
      aws-appsync:
        patterns:
          - "aws-appsync-*"
          - "@apollo/client"
          - "@aws-sdk/client-appsync"
      dotenv:
        patterns:
          - "dotenv*"
      vue:
        patterns:
          - "vue*"
          - "@vue*"
          - "@volar/vue-typescript"
        exclude-patterns:
          - "@vue/eslint-config-prettier"

      vite:
        patterns:
          - "vite*"
          - "@vitejs*"
      prettier:
        patterns:
          - "prettier*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
