AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync

Parameters:
  ProjectName:
    Type: String

Resources:
  # DynamoDB
  TablesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables.template.yaml
      Parameters:
        UserTableName: !Sub ${ProjectName}-user-table
        SessionTableName: !Sub ${ProjectName}-session-table
        PlayerTableName: !Sub ${ProjectName}-player-table
        DashboardTableName: !Sub ${ProjectName}-dashboard-table
        SessionDataTableName: !Sub ${ProjectName}-session-data-table

  # ServiceRole
  ServiceRoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service-role.template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        UserTableArn: !GetAtt TablesStack.Outputs.UserTableArn
        SessionTableArn: !GetAtt TablesStack.Outputs.SessionTableArn
        PlayerTableArn: !GetAtt TablesStack.Outputs.PlayerTableArn
        DashboardTableArn: !GetAtt TablesStack.Outputs.DashboardTableArn
        SessionDataTableArn: !GetAtt TablesStack.Outputs.SessionDataTableArn

Outputs:
  ServiceRoleArn:
    Description: Write this value in samconfig.toml of 2.app-sync and start the stack
    Value: !GetAtt ServiceRoleStack.Outputs.ServiceRoleArn
