AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: stack initializer

Resources:
  InitTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: waddlefy-init
      BillingMode: PAY_PER_REQUEST
      ImportSourceSpecification:
        InputCompressionType: NONE
        InputFormat: CSV
        S3BucketSource:
          S3Bucket: 'arn:aws:s3:::waddlefy-dynamodb-init-data'
          S3BucketOwner: 966748163945
          S3KeyPrefix: 'db-'
      AttributeDefinitions:
        - AttributeName: start
          AttributeType: S
      KeySchema:
        - AttributeName: start
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  InitializerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/nodejs
      Handler: initializer.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Lambda Initializer
      FunctionName: initializer
      Events:
        InitTableStream:
          Type: DynamoDB
          Properties:
            BatchSize: 100
            BisectBatchOnFunctionError: true
            MaximumRetryAttempts: 3
            StartingPosition: TRIM_HORIZON
            Stream: !GetAtt InitTable.StreamArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External: []
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - initializer.ts

  InitializerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${InitializerFunction}
      RetentionInDays: 3
