AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: waddlefy root template

Resources:
  # CloudWatch
  CloudWatchStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-watch.template.yaml

  # OAI
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  # CloudFront
  CloudFrontDistributionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-front.template.yaml
      Parameters:
        RESTApiDomainName: !GetAtt RESTApiStack.Outputs.DomainName
        StaticBucketDomainName: !GetAtt StaticBucketStack.Outputs.RegionalDomainName
        RoomBucketDomainName: !GetAtt RoomBucketStack.Outputs.RegionalDomainName
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # S3
  StaticBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-static.template.yaml
      Parameters:
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id
  RoomBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-room.template.yaml
      Parameters:
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # REST API
  RESTApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest-api/template.yaml
      Parameters:
        GraphQLUrl: !GetAtt AppSyncStack.Outputs.GraphQLUrl

  # AppSync
  AppSyncStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: app-sync/template.yaml

Outputs:
  GraphQLUrl:
    Description: AppSync Endpoint
    Value: !GetAtt AppSyncStack.Outputs.GraphQLUrl
  CloudFrontAccessUrl:
    Value: !GetAtt CloudFrontDistributionStack.Outputs.AccessUrl
  RESTApiDirectUrl:
    Description: To call the REST API by API Gateway.
    Value: !GetAtt RESTApiStack.Outputs.RESTApiDirectUrl
