AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy schema relations

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String
  SessionTableDataSourceName:
    Type: String
  PlayerTableDataSourceName:
    Type: String
  PaneTableDataSourceName:
    Type: String

Resources:
  # UserForUser.firstSession
  RelationUserForUserFirstSession:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: UserForUser
      FieldName: firstSession
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt QueryFirstSessionIdFunction.FunctionId
          - !GetAtt GetSessionFunction.FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplateS3Location: vtl/return-stash-session.vm

  QueryFirstSessionIdFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: query_first_session_id_function
      DataSourceName: !Ref SessionTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: vtl/query-where-user-id-source-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        #set($flg = $ctx.result.items.size() > 0)
        $util.validate($flg, "No such Session")
        $util.qr($ctx.stash.put("sessionId", $ctx.result.items[0].id))
        {}

  GetSessionFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: get_session_function
      DataSourceName: !Ref SessionTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: vtl/get-item-where-id-stash-session-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        $util.qr($ctx.stash.put("session", $ctx.result))
        {}

  # UserForUser.sessions
  RelationUserForUserSessions:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: UserForUser
      FieldName: sessions
      DataSourceName: !Ref SessionTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-user-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # SessionForUser.user
  RelationSessionForUserUser:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForUser
      FieldName: user
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-user-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm

  # SessionForUser.players
  RelationSessionForUserPlayers:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForUser
      FieldName: players
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-session-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # SessionForUser.panes
  RelationSessionForUserPanes:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForUser
      FieldName: panes
      DataSourceName: !Ref PaneTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-session-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # SessionForPlayer.user
  RelationSessionForPlayerUser:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForPlayer
      FieldName: user
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-user-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm

  # SessionForPlayer.players
  RelationSessionForPlayerPlayers:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForPlayer
      FieldName: players
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-session-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # SessionForPlayer.panes
  RelationSessionForPlayerPanes:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: SessionForPlayer
      FieldName: panes
      DataSourceName: !Ref PaneTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-session-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # PlayerForPlayer.session
  RelationPlayerForPlayerSession:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: PlayerForPlayer
      FieldName: session
      DataSourceName: !Ref SessionTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-session-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm
