AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy schema relations

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String
  DashboardTableDataSourceName:
    Type: String
  PlayerTableDataSourceName:
    Type: String
  PaneTableDataSourceName:
    Type: String

Resources:
  # UserForUser.firstDashboard
  RelationUserForUserFirstDashboard:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: UserForUser
      FieldName: firstDashboard
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt QueryFirstDashboardIdFunction.FunctionId
          - !GetAtt GetDashboardFunction.FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplateS3Location: vtl/return-stash-dashboard.vm

  QueryFirstDashboardIdFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: query_first_dashboard_id_function
      DataSourceName: !Ref DashboardTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: vtl/query-where-user-id-source-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        #set($flg = $ctx.result.items.size() > 0)
        $util.validate($flg, "No such Dashboard")
        $util.qr($ctx.stash.put("dashboardId", $ctx.result.items[0].id))
        {}

  GetDashboardFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: get_dashboard_function
      DataSourceName: !Ref DashboardTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: vtl/get-item-where-id-stash-dashboard-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        $util.qr($ctx.stash.put("dashboard", $ctx.result))
        {}

  # UserForUser.dashboards
  RelationUserForUserDashboards:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: UserForUser
      FieldName: dashboards
      DataSourceName: !Ref DashboardTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-user-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # DashboardForUser.user
  RelationDashboardForUserUser:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForUser
      FieldName: user
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-user-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm

  # DashboardForUser.players
  RelationDashboardForUserPlayers:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForUser
      FieldName: players
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-dashboard-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # DashboardForUser.panes
  RelationDashboardForUserPanes:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForUser
      FieldName: panes
      DataSourceName: !Ref PaneTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-dashboard-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # DashboardForPlayer.user
  RelationDashboardForPlayerUser:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForPlayer
      FieldName: user
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-user-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm

  # DashboardForPlayer.players
  RelationDashboardForPlayerPlayers:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForPlayer
      FieldName: players
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-dashboard-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # DashboardForPlayer.panes
  RelationDashboardForPlayerPanes:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: DashboardForPlayer
      FieldName: panes
      DataSourceName: !Ref PaneTableDataSourceName
      RequestMappingTemplateS3Location: vtl/query-where-dashboard-id-source-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result-items.vm

  # PlayerForPlayer.dashboard
  RelationPlayerForPlayerDashboard:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: PlayerForPlayer
      FieldName: dashboard
      DataSourceName: !Ref DashboardTableDataSourceName
      RequestMappingTemplateS3Location: vtl/get-item-where-id-source-dashboard-id.vm
      ResponseMappingTemplateS3Location: vtl/return-result.vm
