AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy Schema

Parameters:
  ServiceRoleArn:
    Type: String
  ApiId:
    Type: String
  UserTableName:
    Type: String
  DashboardTableName:
    Type: String
  PlayerTableName:
    Type: String
  PaneTableName:
    Type: String

Resources:
  # DataSource
  UserTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: UserTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref UserTableName
        AwsRegion: !Ref AWS::Region
  DashboardTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: DashboardTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref DashboardTableName
        AwsRegion: !Ref AWS::Region
  PlayerTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: PlayerTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref PlayerTableName
        AwsRegion: !Ref AWS::Region
  PaneTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: PaneTableDataSource
      ApiId: !Ref ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ServiceRoleArn
      DynamoDBConfig:
        TableName: !Ref PaneTableName
        AwsRegion: !Ref AWS::Region

  # Relations
  RelationsResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: relations.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name
        PaneTableDataSourceName: !GetAtt PaneTableDataSource.Name

  # Functions
  FunctionsResolverStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: functions.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # query checkDuplicateUserId
  MutationCheckDuplicateUserIdStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/check-duplicate-user-id.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name

  # mutation userSignUp
  MutationUserSignUpStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/user-sign-up.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name

  # mutation userSignIn
  MutationUserSignInStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/user-sign-in.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        UserTableDataSourceName: !GetAtt UserTableDataSource.Name

  # mutation addDashboard
  MutationAddDashboardStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/add-dashboard.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name

  # mutation addPlayerByUser
  MutationAddPlayerByUserStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/add-player-by-user.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name
        CheckNoPlayerNameExistsFunctionId: !GetAtt FunctionsResolverStack.Outputs.CheckNoPlayerNameExistsFunctionId

  # mutation addPlayerByPlayer
  MutationPlayerSignUpStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/add-player-by-player.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name
        CheckNoPlayerNameExistsFunctionId: !GetAtt FunctionsResolverStack.Outputs.CheckNoPlayerNameExistsFunctionId

  # mutation playerFirstSignIn
  MutationPlayerFirstSignInStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/player-first-sign-in.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # mutation playerSignIn
  MutationPlayerSignInStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/player-sign-in.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # mutation generatePlayerResetCode
  MutationGeneratePlayerResetCodeStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/generate-player-reset-code.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableName: !Ref PlayerTableName

  # mutation resetPlayerPassword
  MutationResetPlayerPasswordStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: mutation/reset-player-password.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # query directPlayerAccess
  QueryDirectPlayerAccess:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/direct-player-access.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # query directDashboardAccess
  QueryDirectDashboardAccess:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/direct-dashboard-access.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        DashboardTableDataSourceName: !GetAtt DashboardTableDataSource.Name

  # query getDashboardPlayer
  QueryGetDashboardPlayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/get-dashboard-player.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name

  # query getDashboardPlayers
  QueryGetDashboardPlayers:
    Type: AWS::Serverless::Application
    Properties:
      Location: query/get-dashboard-players.template.yaml
      Parameters:
        ApiId: !Ref ApiId
        PlayerTableDataSourceName: !GetAtt PlayerTableDataSource.Name
