AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Query checkDuplicateUserId

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  CheckDuplicateUserIdQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: checkDuplicateUserId
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/get-item-where-id-args-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        $util.toJson({"ok": $util.isNull($ctx.result)})
