AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  waddlefy
  Sample SAM Template for waddlefy

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  GetUserQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: getUser
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/query-where-token-input-user-token.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result-items-first.vm
