AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Query getSessionPlayers

Parameters:
  ApiId:
    Type: String
  PlayerTableDataSourceName:
    Type: String

Resources:
  GetSessionPlayersQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Query
      FieldName: getSessionPlayers
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/query-where-session-id-identity-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        #if($ctx.result.items.size() > 0)
          #set($end = $ctx.result.items.size() - 1)
          #foreach($i in [0..$end])
            #set($ctx.result.items[$i].hasResetCode = !$util.isNull($ctx.result.items[$i].resetCode))
          #end
        #end
        $util.toJson($ctx.result.items)
