name: diff
description: diff
inputs:
  subdir:
    description: target directory
    required: true
outputs:
  diff-count:
    description: count of diff
    value: ${{ steps.diff.outputs.diff-count }}
runs:
  using: composite
  steps:
    - id: diff
      env:
        TARGET_BRANCH: ${{ github.ref_name }}
      run: |
        git fetch origin ${TARGET_BRANCH}
        count=`git diff origin/main...origin/${TARGET_BRANCH} --name-only --relative=${{ inputs.subdir }} | wc -l`
        echo "diff-count=$(echo $count)" >> $GITHUB_OUTPUT
      shell: bash