AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation addSession

Parameters:
  ApiId:
    Type: String
  SessionTableDataSourceName:
    Type: String

Resources:
  AddSessionMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: addSession
      DataSourceName: !Ref SessionTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/put-item-session.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
