AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation addSessionData

Parameters:
  ApiId:
    Type: String
  SessionDataTableDataSourceName:
    Type: String

Resources:
  AddSessionDataMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: addSessionData
      DataSourceName: !Ref SessionDataTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/put-item-session-data.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
