AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  waddlefy
  Sample SAM Template for waddlefy

Parameters:
  ApiId:
    Type: String
  RoomTableDataSourceName:
    Type: String
  UpdateConnectionRoomFunctionId:
    Type: String

Resources:
  AddRoomMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: entryRoom
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt VerifyRoomPasswordFunction.FunctionId
          - !Ref UpdateConnectionRoomFunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplateS3Location: ../vtl/return-stash-room.vm

  VerifyRoomPasswordFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: verify_room_password_function
      DataSourceName: !Ref RoomTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: ../vtl/get-item-where-id-input-room-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        #if(!$ctx.result || $ctx.result.password != $ctx.args.input.password)
          $util.unauthorized()
        #end
        $util.qr($ctx.stash.put("id", $ctx.result.id))
        $util.qr($ctx.stash.put("room", $ctx.result))
        {}
