AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation generatePlayerResetCode

Parameters:
  ApiId:
    Type: String
  PlayerTableName:
    Type: String

Resources:
  GeneratePlayerResetCodeMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: generatePlayerResetCode
      DataSourceName: !GetAtt GeneratePlayerResetCodeFunctionDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation": "Invoke",
          "payload": $util.toJson($ctx.args)
        }
      ResponseMappingTemplate: $util.toJson($context.result)

  GeneratePlayerResetCodeFunctionDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GeneratePlayerResetCodeFunctionDataSource
      ApiId: !Ref ApiId
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GeneratePlayerResetCodeFunction.Arn
      ServiceRoleArn: !GetAtt AppSyncLambdaInvokeRole.Arn

  GeneratePlayerResetCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../lambda/nodejs
      Handler: generate-player-reset-code.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionName: request-reset-player-password
      Description: Waddlefy AppSync Scheme
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayerTableName
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - generate-player-reset-code.ts

  GeneratePlayerResetCodeFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GeneratePlayerResetCodeFunction}
      RetentionInDays: 3

  AppSyncLambdaInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowInvokeLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:invokeFunction
                Resource: !GetAtt GeneratePlayerResetCodeFunction.Arn