AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation updateSession

Parameters:
  ApiId:
    Type: String
  SessionTableDataSourceName:
    Type: String

Resources:
  UpdateSessionMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updateSession
      DataSourceName: !Ref SessionTableDataSourceName
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "id" : $util.dynamodb.toDynamoDBJson($ctx.args.input.sessionId)
          },
          "update" : {
            "expression" : "SET #name = :name, #sessionType = :sessionType",
            "expressionNames" : {
              "#name" : "name",
              "#sessionType" : "sessionType",
            },
            "expressionValues" : {
              ":name" : $util.dynamodb.toDynamoDBJson($ctx.args.input.name),
              ":sessionType" : $util.dynamodb.toDynamoDBJson($ctx.args.input.sessionType),
            }
          }
        }
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
