AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation updatePlayerName

Parameters:
  ApiId:
    Type: String
  PlayerTableDataSourceName:
    Type: String

Resources:
  UpdatePlayerNameMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updatePlayerName
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/update-item-name-input-name-where-id-identity-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
