AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy Lambda Authorizer

Parameters:
  ProjectName:
    Type: String
  UserTableName:
    Type: String
  SessionTableName:
    Type: String
  PlayerTableName:
    Type: String

Resources:
  AppSyncAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/nodejs
      Handler: authorizer.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionName: !Sub ${ProjectName}-appsync-authorizer
      Description: Waddlefy AppSync Authorizer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayerTableName
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTableName
          SESSION_TABLE_NAME: !Ref SessionTableName
          PLAYER_TABLE_NAME: !Ref PlayerTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - authorizer.ts

  AppSyncAuthorizerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppSyncAuthorizer}
      RetentionInDays: 3

Outputs:
  Arn:
    Value: !GetAtt AppSyncAuthorizer.Arn
