AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy Lambda DataClean

Parameters:
  ProjectName:
    Type: String
  UserTableName:
    Type: String
  SessionTableName:
    Type: String
  SessionDataTableName:
    Type: String
  PlayerTableName:
    Type: String
  DashboardTableName:
    Type: String

Resources:
  DataClean:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/nodejs
      Handler: data-clean.handler
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      FunctionName: !Sub ${ProjectName}-data-clean
      Description: Waddlefy Data Clean
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionDataTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayerTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref DashboardTableName
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserTableName
          SESSION_TABLE_NAME: !Ref SessionTableName
          SESSION_DATA_TABLE_NAME: !Ref SessionDataTableName
          PLAYER_TABLE_NAME: !Ref PlayerTableName
          DASHBOARD_TABLE_NAME: !Ref DashboardTableName
      Events:
        ScheduleJob:
          Type: Schedule
          Properties:
            Name: !Sub ${ProjectName}-data-clean-schedule
            Schedule: cron(0 21 ? * 1 *)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        External:
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
        Minify: false
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - data-clean.ts

  AppSyncAuthorizerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DataClean}
      RetentionInDays: 3

