AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync

Parameters:
  ProjectName:
    Type: String
  ServiceRoleArn:
    Type: String

Resources:
  AppSync:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref ProjectName
      AuthenticationType: AWS_LAMBDA
      LambdaAuthorizerConfig:
        AuthorizerUri: !GetAtt AuthorizerStack.Outputs.Arn
        IdentityValidationExpression: .*

  # Schema
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSync.ApiId
      DefinitionS3Location: schema.graphql

  # 認証ロジック
  AuthorizerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: authorizer.template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        UserTableName: !Sub ${ProjectName}-user-table
        SessionTableName: !Sub ${ProjectName}-session-table
        PlayerTableName: !Sub ${ProjectName}-player-table

  # データクリーンロジック
  DataCleanStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: data-clean.template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        UserTableName: !Sub ${ProjectName}-user-table
        SessionTableName: !Sub ${ProjectName}-session-table
        SessionDataTableName: !Sub ${ProjectName}-session-data-table
        PlayerTableName: !Sub ${ProjectName}-player-table
        DashboardTableName: !Sub ${ProjectName}-dashboard-table

  AppsyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AuthorizerStack.Outputs.Arn
      Action: lambda:InvokeFunction
      Principal: appsync.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref AppSync

  SchemaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: schema/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        ApiId: !GetAtt AppSync.ApiId
        ServiceRoleArn: !Ref ServiceRoleArn
        UserTableName: !Sub ${ProjectName}-user-table
        SessionTableName: !Sub ${ProjectName}-session-table
        PlayerTableName: !Sub ${ProjectName}-player-table
        DashboardTableName: !Sub ${ProjectName}-dashboard-table
        SessionDataTableName: !Sub ${ProjectName}-session-data-table
    DependsOn:
      - AppSyncSchema

Outputs:
  GraphQLUrl:
    Description: Write this value in samconfig.toml of 3.client and start the stack
    Value: !GetAtt AppSync.GraphQLUrl
