AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy DynamoDB tables

Parameters:
  UserTableName:
    Type: String
  SessionTableName:
    Type: String
  PlayerTableName:
    Type: String
  DashboardTableName:
    Type: String
  SessionDataTableName:
    Type: String

Resources:
  # User Table
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref UserTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - secret

  # Session Table
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
        - AttributeName: signUpToken
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref SessionTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - name
        - IndexName: signUpToken-index
          KeySchema:
            - AttributeName: signUpToken
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  # Player Table
  PlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref PlayerTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - secret
        - IndexName: session-name-index
          KeySchema:
            - AttributeName: name
              KeyType: HASH
            - AttributeName: sessionId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: sessionId-index
          KeySchema:
            - AttributeName: sessionId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - name
              - iconToken
              - status

  # Dashboard Table
  DashboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref DashboardTableName
      GlobalSecondaryIndexes:
        - IndexName: sessionId-index
          KeySchema:
            - AttributeName: sessionId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # SessionData Table
  SessionDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref SessionDataTableName
      GlobalSecondaryIndexes:
        - IndexName: sessionId-index
          KeySchema:
            - AttributeName: sessionId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UserTableArn:
    Value: !GetAtt UserTable.Arn
  SessionTableArn:
    Value: !GetAtt SessionTable.Arn
  PlayerTableArn:
    Value: !GetAtt PlayerTable.Arn
  DashboardTableArn:
    Value: !GetAtt DashboardTable.Arn
  SessionDataTableArn:
    Value: !GetAtt SessionDataTable.Arn
