AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy DynamoDB tables

Parameters:
  UserTableName:
    Type: String
  DashboardTableName:
    Type: String
  PlayerTableName:
    Type: String
  PaneTableName:
    Type: String

Resources:
  # User Table
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref UserTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - secret

  # Dashboard Table
  DashboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
        - AttributeName: signUpToken
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref DashboardTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - name
        - IndexName: signUpToken-index
          KeySchema:
            - AttributeName: signUpToken
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  # Player Table
  PlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: token
          AttributeType: S
        - AttributeName: dashboardId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref PlayerTableName
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - secret
        - IndexName: dashboard-name-index
          KeySchema:
            - AttributeName: name
              KeyType: HASH
            - AttributeName: dashboardId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: dashboardId-index
          KeySchema:
            - AttributeName: dashboardId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - name

  # Pane Table
  PaneTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: dashboardId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref PaneTableName
      GlobalSecondaryIndexes:
        - IndexName: dashboardId-index
          KeySchema:
            - AttributeName: dashboardId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UserTableArn:
    Value: !GetAtt UserTable.Arn
  DashboardTableArn:
    Value: !GetAtt DashboardTable.Arn
  PlayerTableArn:
    Value: !GetAtt PlayerTable.Arn
  PaneTableArn:
    Value: !GetAtt PaneTable.Arn
