AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync

Parameters:
  UserTableName:
    Type: String
    Default: waddlefy-user-table
  SessionTableName:
    Type: String
    Default: waddlefy-session-table
  PlayerTableName:
    Type: String
    Default: waddlefy-player-table
  DashboardTableName:
    Type: String
    Default: waddlefy-dashboard-table
  SessionDataTableName:
    Type: String
    Default: waddlefy-session-data-table

Resources:
  AppSync:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: waddlefy
      AuthenticationType: AWS_LAMBDA
      LambdaAuthorizerConfig:
        AuthorizerUri: !GetAtt AuthorizerStack.Outputs.Arn
        IdentityValidationExpression: .*

  # Schema
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSync.ApiId
      DefinitionS3Location: schema.graphql

  # 認証ロジック
  AuthorizerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: authorizer.template.yaml
      Parameters:
        UserTableName: !Ref UserTableName
        SessionTableName: !Ref SessionTableName
        PlayerTableName: !Ref PlayerTableName

  AppsyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AuthorizerStack.Outputs.Arn
      Action: lambda:InvokeFunction
      Principal: appsync.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref AppSync

  # ServiceRole
  ServiceRoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service-role.template.yaml
      Parameters:
        UserTableArn: !GetAtt TablesStack.Outputs.UserTableArn
        SessionTableArn: !GetAtt TablesStack.Outputs.SessionTableArn
        PlayerTableArn: !GetAtt TablesStack.Outputs.PlayerTableArn
        DashboardTableArn: !GetAtt TablesStack.Outputs.DashboardTableArn
        SessionDataTableArn: !GetAtt TablesStack.Outputs.SessionDataTableArn

  # DynamoDB
  TablesStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables.template.yaml
      Parameters:
        UserTableName: !Ref UserTableName
        SessionTableName: !Ref SessionTableName
        PlayerTableName: !Ref PlayerTableName
        DashboardTableName: !Ref DashboardTableName
        SessionDataTableName: !Ref SessionDataTableName

  SchemaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: schema/template.yaml
      Parameters:
        ApiId: !GetAtt AppSync.ApiId
        ServiceRoleArn: !GetAtt ServiceRoleStack.Outputs.ServiceRoleArn
        UserTableName: !Ref UserTableName
        SessionTableName: !Ref SessionTableName
        PlayerTableName: !Ref PlayerTableName
        DashboardTableName: !Ref DashboardTableName
        SessionDataTableName: !Ref SessionDataTableName
    DependsOn:
      - AppSyncSchema

Outputs:
  GraphQLUrl:
    Description: AppSync Endpoint
    Value: !GetAtt AppSync.GraphQLUrl
