AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation deletePlayer

Parameters:
  ApiId:
    Type: String
  PlayerTableDataSourceName:
    Type: String

Resources:
  DeletePlayerMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: deletePlayer
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/delete-item-where-id-input-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
