AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation updateUserName

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  UpdateUserNameMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updateUserName
      DataSourceName: !Ref UserTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/update-item-name-input-name-where-id-input-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
