AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation updatePlayerIcon

Parameters:
  ApiId:
    Type: String
  PlayerTableDataSourceName:
    Type: String

Resources:
  UpdatePlayerIconMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: updatePlayerIcon
      DataSourceName: !Ref PlayerTableDataSourceName
      RequestMappingTemplateS3Location: ../vtl/update-item-icon-token-auto-id-where-id-identity-id.vm
      ResponseMappingTemplateS3Location: ../vtl/return-result.vm
