AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy AppSync Mutation userSignIn

Parameters:
  ApiId:
    Type: String
  UserTableDataSourceName:
    Type: String

Resources:
  UserSignInMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref ApiId
      TypeName: Mutation
      FieldName: userSignIn
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt VerifyUserPasswordFunction.FunctionId
          - !GetAtt UpdateUserBySignInFunction.FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplateS3Location: ../vtl/return-stash-user.vm

  VerifyUserPasswordFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: verify_user_password_function
      DataSourceName: !Ref UserTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: ../vtl/get-item-where-id-input-user-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        #if(!$ctx.result || $ctx.result.password != $ctx.args.input.password)
          $util.unauthorized()
        #end
        $util.qr($ctx.stash.put("id", $ctx.result.id))
        $util.qr($ctx.stash.put("user", $ctx.result))
        {}

  UpdateUserBySignInFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: !Ref ApiId
      Name: update_user_by_sign_in_function
      DataSourceName: !Ref UserTableDataSourceName
      FunctionVersion: 2018-05-29
      RequestMappingTemplateS3Location: ../vtl/update-item-last-logged-in-now-where-id-stash-id.vm
      ResponseMappingTemplate: |
        #if($ctx.result && $ctx.result.error)
          $util.error($ctx.result.error)
        #end
        $util.qr($ctx.stash.put("user", $ctx.result))
        {}
