AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: waddlefy Lambda 'appsync-connect-info'

Parameters:
  GraphQLUrl:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/nodejs
      Handler: app-sync-connect-info.handler
      FunctionName: appsync-connect-info
      Tracing: Active
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          GRAPHQL_URL: !Ref GraphQLUrl
          REGION: !Ref AWS::Region
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        Target: es2022
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - app-sync-connect-info.ts

  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref LambdaFunction
      Principal: "apigateway.amazonaws.com"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}
      RetentionInDays: 3

Outputs:
  FunctionArn:
    Value: !GetAtt LambdaFunction.Arn
