name: Deploy AppSync

on:
  push:
    paths:
      - 'sam/2.app-sync/**'
      - 'sam/lambda/**'
    branches-ignore:
      - 'images'
      - 'dependabot/npm_and_yarn/**'
  workflow_dispatch:

env:
  PROJECT_NAME: ${{ github.ref == 'refs/heads/main' && 'waddlefy' || 'dev-waddlefy' }}
  SERVICE_ROLE_ARN: ${{ github.ref == 'refs/heads/main' && secrets.AWS_SERVICE_ROLE_ARN || secrets.AWS_SERVICE_ROLE_ARN_DEV }}

jobs:
  deploy:
    name: Deploy AppSync to ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: setup python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      - name: setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./sam/lambda/nodejs/package-lock.json
      - run: npm i
        working-directory: ./sam/lambda/nodejs
      - run: npm i -g esbuild wscat
      - name: setup sam
        uses: aws-actions/setup-sam@342dcc4899c07fedf41f91cbb1e6c68925a85d37 # v2
      - name: aws config
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: build
        run: sam build
        working-directory: ./sam/2.app-sync
      - name: deploy
        run: |
          sam deploy --stack-name ${{ env.PROJECT_NAME }}-app-sync \
          --s3-bucket sam-deploy-source-waddlefy \
          --force-upload \
          --s3-prefix ${{ env.PROJECT_NAME }} \
          --parameter-overrides ProjectName=${{ env.PROJECT_NAME }} ServiceRoleArn=${{ env.SERVICE_ROLE_ARN }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
        working-directory: ./sam/2.app-sync
