name: formatter

on: push

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - name: npm install
        working-directory: ./client
        run: npm i --force
      - name: Run Prettier
        working-directory: ./client
        run: npm run format:ci
