AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Waddlefy client

Parameters:
  GraphQLUrl:
    Type: String

Resources:
  # CloudWatch
  CloudWatchStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-watch.template.yaml

  # OAI
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

  # S3
  StaticBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-static.template.yaml
      Parameters:
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id
  RoomBucketStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-room.template.yaml
      Parameters:
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # CloudFront
  CloudFrontDistributionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloud-front.template.yaml
      Parameters:
        RESTApiDomainName: !GetAtt ApiGatewayRESTApiStack.Outputs.DomainName
        StaticBucketDomainName: !GetAtt StaticBucketStack.Outputs.RegionalDomainName
        RoomBucketDomainName: !GetAtt RoomBucketStack.Outputs.RegionalDomainName
        OAI: !GetAtt CloudFrontOriginAccessIdentity.Id

  # API Gateway
  ApiGatewayRESTApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: gateway.template.yaml
      Parameters:
        AppSyncConnectInfoFunctionArn: !GetAtt AppSyncConnectInfoFunctionStack.Outputs.FunctionArn

  # Lambda
  AppSyncConnectInfoFunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: app-sync-connect-info.template.yaml
      Parameters:
        GraphQLUrl: !Ref GraphQLUrl

Outputs:
  CloudFrontAccessUrl:
    Value: !GetAtt CloudFrontDistributionStack.Outputs.AccessUrl
  RESTApiDirectUrl:
    Value: !GetAtt ApiGatewayRESTApiStack.Outputs.ProdDataEndpoint
